export const CREATE_USER = 'CREATE_USER';

export const LOGIN_USER = 'LOGIN_USER';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

export const GET_USER = 'GET_USER';
